application: theschrift
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /
  script: application.notebook.app

- url: /about
  script: application.notebook.app

- url: /contact
  script: application.notebook.app

- url: /.*
  script: application.handlers.404.app

libraries:
- name: jinja2
  version: 2.6